#!/usr/bin/env bash
set -euo pipefail

# shellcheck source=/dev/null
. "$PARA_HELPERS"

stage "GitHub CLI"
xbps_install github-cli >/dev/null
mkdir -p /usr/share/zsh/site-functions
gh completion -s zsh > /usr/share/zsh/site-functions/_gh
